library(dplyr)
MPGdataframe <- read.csv(file='MechaCar_mpg.csv', stringsAsFactors = FALSE)
lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=MPGdataframe)
summary(lm(mpg ~ vehicle_length + vehicle_weight + spoiler_angle + ground_clearance + AWD, data=MPGdataframe))
SuspensionTable <- read.csv(file='Suspension_Coil.csv', stringsAsFactors = TRUE)
SuspensionTableSummary <- SuspensionTable %>% summarize(PSI_Mean = mean(PSI), PSI_Median = median(PSI), PSI_var = var(PSI), PSI_sd = sd(PSI)) 
lot_summary <- SuspensionTable %>% group_by(Manufacturing_Lot) %>% summarize(PSI_Mean = mean(PSI), PSI_Median = median(PSI), PSI_var = var(PSI), PSI_sd = sd(PSI)) 
t.test((SuspensionTable$PSI),mu=1500)
Lot1_Data <- subset(SuspensionTable, SuspensionTable$Manufacturing_Lot == "Lot1")
Lot2_Data <- subset(SuspensionTable, SuspensionTable$Manufacturing_Lot == "Lot2")
Lot3_Data <- subset(SuspensionTable, SuspensionTable$Manufacturing_Lot == "Lot3")
t.test(Lot1_Data$PSI, mu=1500)
t.test(Lot2_Data$PSI, mu=1500)
t.test(Lot3_Data$PSI, mu=1500)
